### ISSUE TITLE
New PyPI release with updated Python versions?

### ISSUE THREAD

**Issue by ntamas** [IMRCLab/libmotioncapture#11]
First of all, thanks for this great package, it saved me a lot of time when developing mocap support for Crazyflie drones in Skybrush (see [here](https://github.com/skybrush-io/skybrush-ext-libmotioncapture) for the Skybrush server extension where we use `libmotioncapture`).

Is there any chance for a new release on PyPI with the recent commits, targeted at newer Python versions (3.10 and 3.11)? Version 1.0a1 has support only up to Python 3.9. If you don't have time for this but you are willing to accept a PR, let me know and I'll look into this. Ultimately, I'd like to make sure that `motioncapture` is `pip`-installable on Python 3.10 and 3.11 as we intend to move on to newer Python versions.

**Comment by krichardsson** [comment]
I agree, yes please make it compatible with later python versions :-)

I was looking a bit at using it in the python lib (https://github.com/bitcraze/crazyflie-lib-python/issues/411) but also bumped into this problem .

**Comment by whoenig** [comment]
In principle this should be easy (see https://github.com/IMRCLab/libmotioncapture/pull/13), but currently the Mac doesn't work in CI (simply times out). Have you had this problem before @krichardsson ?

**Comment by whoenig** [comment]
Nevermind Kristoffer, I found it. The code here is actually almost identically to the one at https://github.com/bitcraze/crazyflie-link-cpp, which was updated earlier. Good idea with having a weekly cron-job, too.

**Comment by whoenig** [comment]
There is a new release now, including for Python 3.10 and 3.11.
