### ISSUE TITLE
no received rigid bodies from qualisys

### ISSUE THREAD

**Issue by knmcguire** [IMRCLab/libmotioncapture#3]
Hi!

In light of our christmas video we wanted to use Crazyswarm but noticed that the qualisys frames weren't received properly. We recently updated the QTM tracker software, but that does not seem to be it, as the qualisys cpp library in deps folder. seems to be able to receive the rigid bodies fine.

This happens in ./motioncapture_example "qualisys" <ip address>, and I looked at [this value](https://github.com/IMRCLab/libmotioncapture/blob/0578d2322f012802b68dc5046cf9826ad4afd464/src/qualisys.cpp#L91) during debugging, it stays zero, also if I update the qualisys cpp library to the latest master.

Using ubuntu 20.04 and the CPP version of this lib. Probably since we are one of the few that got qualisys we will probably need to fix this ourselves but if there is any pointers, please let us know :smile:

**Comment by knmcguire** [comment]
Just some more clarification, we are receiving frames but the rigid bodies in those are not recognized in the lib, while the qualisys rigid body streamer example on the same computer is able to see them.

**Comment by whoenig** [comment]
There was always some deprecation warning when compiling - maybe we are using the library 'wrong' now. This support was originally implemented by Arnaud, by the way.

Compared to the latest official example, we don't explicitly enable streaming of frames (see https://github.com/qualisys/qualisys_cpp_sdk/blob/master/RigidBodyStreaming/RigidBodyStreaming.cpp#L70). I could imagine this a problem, if the default changed in between versions.

**Comment by whoenig** [comment]
Feel free to test https://github.com/IMRCLab/libmotioncapture/tree/issue3. The other problem in the code was that the paketPointer was never updated.

**Comment by knmcguire** [comment]
thanks for the pointers! I'll give it another go once I'm at the office. @ataffanel was also away for a while but came back this week so hopefully we will be able to look at it together.

**Comment by knmcguire** [comment]
Hi! Sorry it took a bit long to look at this again, but it doesn not work yet with the issue3 branch. I only see this:
```
./motioncapture_example "qualisys" 192.168.5.21 
supportsRigidBodyTracking: 1
supportsLatencyEstimate: 0
supportsPointCloud: 1
supportsTimeStamp: 1
```
but not printouts of the rigid bodies, eventhough with the qualisys example in deps folder I see this:

```
./RigidBodyStreaming 
Starting to streaming 6DOF data

Frame 64055
======================================================================================================================
cf3          Pos:   -73.522  -432.958    18.698    Rot:  0.123  0.992 -0.013 -0.992  0.124  0.040  0.041  0.008  0.999
```

As I'm traveling tomorrow, I'll won't be able to check this out anymore in our arena until January, so hopefully @ataffanel will be able to help out to then.

**Comment by shreeram-murali** [comment]
Hi! 

I raised a similar issue in [crazyswarm#571](https://github.com/USC-ACTLab/crazyswarm/discussions/571) and tried out libmotioncapture's example to see the same output as yours:

```
./motioncapture_example qualisys 192.168.0.106
supportsRigidBodyTracking: 1
supportsLatencyEstimate: 0
supportsPointCloud: 1
supportsTimeStamp: 1

```

I also had the same deprecation warning that @whoenig mentioned while building the Qualisys CPP objects.

```
/home/shree-ws/libmotioncapture/src/qualisys.cpp: In member function ‘virtual void libmotioncapture::MotionCaptureQualisys::waitForNextFrame()’:
/home/shree-ws/libmotioncapture/src/qualisys.cpp:82:54: warning: ‘int CRTProtocol::ReceiveRTPacket(CRTPacket::EPacketType&, bool, int)’ is deprecated: Replaced by Receive. [-Wdeprecated-declarations]
       pImpl->poRTProtocol.ReceiveRTPacket(eType, true);
                                                      ^
In file included from /home/shree-ws/libmotioncapture/src/qualisys.cpp:8:0:
/home/shree-ws/libmotioncapture/deps/qualisys_cpp_sdk/RTProtocol.h:718:17: note: declared here
     int         ReceiveRTPacket(CRTPacket::EPacketType &eType, bool bSkipEvents = true, int nTimeout = cWaitForDataTimeout); // nTimeout < 0 : Blocking receive

```

**Comment by whoenig** [comment]
This warning should be gone in the issue3 branch. This warning used to always appear, even when qualisys tracking still worked 6 months ago or so.

**Comment by whoenig** [comment]
@knmcguire: with the fix merged, we can close this one now, correct?

**Comment by knmcguire** [comment]
Indeed! Let's close it
